name       : biblesync
version    : 2.0.0
release    : 2
source     :
    - https://github.com/karlkleinpaste/biblesync/releases/download/2.0.0/biblesync-2.0.0.tar.gz : a2b979d6186df60f8ae30cf1862773a33ea276953a18001ec627ff028ab50154
license    : Public-Domain
component  : programming
summary    : BibleSync is a multicast protocol to support Bible software shared co-navigation
description: |
    BibleSync is a multicast protocol to support Bible software shared co-navigation
setup      : |
    %cmake -DBUILD_SHARED_LIBS=1 .
build      : |
    %make
install    : |
    %make_install
